version: '3'
services:
  web:
    container_name: web
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./:/app
      - ./site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
      - mysql
    depends_on:
      - mysql
  php:
    container_name: php
    build:
      dockerfile: dockerfiles/Dockerfile
      context: .
    volumes:
      - ./:/app
  mysql:
    container_name: mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: time-tracker
    ports:
      - "3306:3306"
